# Generated by Django 4.2.7 on 2023-11-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
